### ISSUE TITLE
Reordering quantifiers disturbs smt tactic

### ISSUE THREAD

**Issue by threonorm** [smtcoq/smtcoq#135]
Hi!

First, thank you for your work! I was trying to prove a small theorem, and I observe some brittleness with the order of quantifications and was looking for some guidelines I could follow to work around the issue.

Here is a small, successful snippet :

```Coq 
Section test.
        Hypothesis (HG: CompDec (list Z)).
        Local Notation "a ==? b" := (@eqb_of_compdec (list Z) HG a b) (at level 45).
        Hypothesis (h1 : forall (l l' : list Z) (x x' : Z), (x :: l) ==? (x' :: l') ---> (l ==? l')) .
        Hypothesis (h1' : forall (l l' : list Z) (x x' : Z), (x :: l) ==? (x' :: l') ---> (x =? x') ) .
        
        
        Hypothesis (h2 : forall (x : Z) y, negb ([] ==? (x ::y))).
        Hypothesis (h3 : forall (l : list Z) , (l ==? []) || (l ==? (proj21 l :: proj22 l))) .
        Hypothesis (h4 :  forall (l : list Z) m, l ==? [] --->  (l ++ m) ==? m) .
        Hypothesis (h5 :  forall  m  (l1 : list Z) (l : list Z) a , l ==? (a :: l1) ---> (l ++ m) ==? (a :: (l1 ++ m))) .
        Add_lemmas h1 h1' h3 h2 h4 h5.
        Theorem app_eq_unit_auto :
            forall  (x y: list Z) (a:Z),
              (x ++ y) = nil -> 
                (x = []).
          Proof. 
          intros.
          smt. (* Works*)
          Qed.

```

Though if I replace h5 by the following (just reversing the two forall l, l1 quantifiers):

```Coq
Hypothesis (h5 :  forall  m  (l : list Z) (l1 : list Z) a , l ==? (a :: l1) ---> (l ++ m) ==? (a :: (l1 ++ m))) .
```

The smt tactic crashes. 
When calling `verit` I get a clearer error: " VeritSyntax.ml: rule tmp_qnt_simplify not implemented yet".

Would there be any guidelines on how to avoid such unsupported proof rules?  
(I used ==? and ---> to avoid potential issues in bool to prop, though the example works/fails the same way if I used -> and =)

**Comment by ckeller** [comment]
Hi @threonorm 
Thanks for reporting! That is indeed a strange behavior that veriT uses the rule `tmp_qnt_simplify` in one case and not in the other case...
I don't think I can give you guidelines since it is very odd. However, this bug will disappear at some point when we switch to a more recent version of veriT thanks to @arjunvish works. (I am thus not going to fix it.)
In case you want to use SMTCoq for automatic tactics, I inform you that there is a new plugin of top on it, called [Sniper](https://github.com/smtcoq/sniper), which improves it a lot. I recommend using [this release](https://github.com/smtcoq/sniper/releases/tag/cpp23) or the development version in [this branch](https://github.com/smtcoq/sniper/tree/coq-8.17-with-trakt). You can look at examples [here](https://github.com/smtcoq/sniper/tree/coq-8.17-with-trakt/examples).

**Comment by threonorm** [comment]
Hi @ckeller, 

Thank you for your answer! No problem.

Yes, I am actually coming to SMTCoq from discovering Sniper, though I have ported the (relatively big) project for which I wanted to play with Sniper/SMTCoq to Coq 8.18, and I saw that Sniper was not yet compatible with Coq 8.18, so I thought maybe before trying to do the port to 8.18, I could try to manually implement the transformation presented in the [paper](https://dl.acm.org/doi/pdf/10.1145/3573105.3575676) to both understand a little how things work and play with it. That also explains why the example above is suspiciously similar to https://github.com/smtcoq/sniper/blob/coq-8.17-with-trakt/examples/examples.v#L94. 

Though, maybe I should just try to run things in 8.18 and see if it can work.

Thanks!
