### ISSUE TITLE
Parse Error when Checking Satisfiability/Unsatisfiability of Problem

### ISSUE THREAD

**Issue by VishalMadipadga** [smtcoq/smtcoq#65]
I am trying to check the result given by cvc4 on a satisfiable problem using the cvc4tocoq shell script found in /src/lfsc/tests

I ran the command.
```
cvc4 name.smt2
```
This is what I got as output.
```
success
success
success
success
success
success
success
success
success
sat
```
This made me think my problem was satisfiable. But when I used the cvc4tocoq shellscript (or even when I did it manually) I got an error. Specifically, I ran this command 
```
./cvc4tocoq name.smt2
```
The resulting output was this,
```
Running CVC4... Done [.014936000 s]
Checking LFSC proof with Coq directly.
File "./name_lfsc.v", line 8, characters 3-40:
Error: Anomaly "Uncaught exception Parsing.Parse_error."
Please report at http://coq.inria.fr/bugs/.
```
The error occurred here
```
Section File.
   Lfsc_Checker "name.smt2" "name.lfsc".
End File.
```

My question was, if a problem is satisfiable, is this the expected output when trying to check the result given by an smt solver on the satisfiable problem?
 
When I was checking the result given by veriT on an unsatisfiable problem, I got what was expected as output.

```
 = true
 : bool
```

Thanks

**Comment by ckeller** [comment]
Hi @VishalMadipadga 
The provability of some theorem in Coq is (somehow) equivalent to the unsatisfiability of the negation of the theorem in SMT. This is why the checker returns "true" for unsatisfiable problems.
The tactics, on goals that fall in the SMTCoq fragment, will either solve the goal (UNSAT case) or provide a counter-example (SAT case).
The `cvc4tocoq` script is mostly used for debugging, which is why it is not designed to provide good error messages.

**Comment by ckeller** [comment]
@VishalMadipadga Did I answered your question?

**Comment by VishalMadipadga** [comment]
I apologize for the late response. So if a Coq theorem is provable, it is unsatisfiable according to the SMT solver?

**Comment by ckeller** [comment]
The provability of a Coq theorem is equivalent to the unsatisfiability of its negation. Thus, given a goal, SMTCoq sends its negation to the SMT solver, and excepts from it to show that it is unsatisfiable. However, the SMT solver may find a model, in which case we can give a counter-example of the Coq theore, or may return that it does not know, since the logic is undecidable.

**Comment by VishalMadipadga** [comment]
Ok, got it. That makes sense. I had one last question if you don't mind. Is there a way to convert verit and cvc4 proofs to Coq proofs using SMTCoq?

**Comment by ckeller** [comment]
The command `Verit_Theorem thm problem.smt2 problem.log.` imports the veriT proof `problem.log` of the problem `problem.smt2` into the Coq theorem `thm`. For CVC4, there is a similar command `Lfsc_Theorem`.

**Comment by VishalMadipadga** [comment]
Thank you for all your help.
